/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adopciones;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rocio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    int id_perro;
    int id_adoptante;
    int id_adopcion;
    Boolean estado=true;
    //defino aqui variable sql ,parametroBUsquedapara que su valor varie en funcion de caso del switch
    String sql;
    String parametroBusqueda;

    DefaultTableModel modeloPerroTabla = new DefaultTableModel();
    DefaultTableModel modeloAdoptanteTabla = new DefaultTableModel();
    DefaultTableModel modeloAdopcionTabla = new DefaultTableModel();
    PerroDAO p = new PerroDAO();
    AdoptanteDAO ate = new AdoptanteDAO();
    AdopcionDAO acion = new AdopcionDAO();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        rellenameTablaPerro();
        rellenameTablaAdoptante();
        rellenameTablaAdopcion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerro = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAdopcion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAdoptante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtFecha_Nacimiento = new javax.swing.JTextField();
        txtDireccionPerrera = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreAdoptante = new javax.swing.JTextField();
        txtPrimerPellidoAdoptante = new javax.swing.JTextField();
        txtSegundoPellidoAdoptante = new javax.swing.JTextField();
        txtDireccionAdoptante = new javax.swing.JTextField();
        txtCiudadAdoptante = new javax.swing.JTextField();
        txtCodigoPostalAdoptante = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmBoxCategoriaBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add Adoptatante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar Perro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaPerro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num chip", "Nombre", "Raza", "Año nacimiento", "Direccion perrera", "Estado adopcion"
            }
        ));
        tablaPerro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPerroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPerro);

        jTabbedPane1.addTab("Perros disponibles", jScrollPane1);

        tableAdopcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopcion numero", "Fecha adopcion", "Perro adoptado", "Adoptante", "direccion adoptante"
            }
        ));
        tableAdopcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdopcionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableAdopcion);

        jTabbedPane1.addTab("Adopciones", jScrollPane3);

        TablaAdoptante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Propietario", "Nombre", "Primer Pellido", "Segundo Apellido", "Direccion", "Ciudad", "CC AA", "CP"
            }
        ));
        TablaAdoptante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAdoptanteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaAdoptante);

        jTabbedPane1.addTab("Adoptantes", jScrollPane2);

        jLabel1.setText("Nombre perro:");

        jLabel2.setText("Raza: ");

        jLabel3.setText("Año nacimiento: ");

        jLabel4.setText("Direccion perrera");

        jButton3.setText("Add Perro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar Perro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jLabel6.setText("Primer Apellido: ");

        jLabel7.setText("Segundo Apellido: ");

        jLabel9.setText("Direccion: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA COMUNIDAD AUTONOMA", "Andalucía", "Aragón", "Principado de Asturias", "Illes Balears", "Canarias", "Cantabria", "Castilla y León", "Castilla-La Mancha", "Cataluña", "Comunitat Valenciana", "Extremadura", "Galicia", "Comunidad de Madrid", "Región de Murcia", "Comunidad Foral de Navarra", "País Vasco", "La Rioja", "Ciudad Autónoma de Ceuta", "Ciudad Autónoma de Melilla" }));

        jLabel10.setText("Ciudad: ");

        jLabel11.setText("Codigo postal: ");

        jButton5.setText("Actualizar Adoptante");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Borrar Adoptante");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Generar Adopcion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Buscar: ");

        cmBoxCategoriaBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA BUSQUEDA", "NOMBRE PERRO", "RAZA", "CIUDAD ADOPTANTE", "CODIGO POSTAL ADOPTANTE", "COMUNIDAD AUTONOMA ADOPTANTE" }));

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar)
                            .addComponent(cmBoxCategoriaBusqueda, 0, 486, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxCategoriaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccionPerrera, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreAdoptante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrimerPellidoAdoptante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSegundoPellidoAdoptante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccionAdoptante))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCiudadAdoptante)
                                    .addComponent(txtCodigoPostalAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreAdoptante, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                            .addComponent(txtNombre)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrimerPellidoAdoptante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundoPellidoAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccionPerrera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccionAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCiudadAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPostalAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaAdoptanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAdoptanteMouseClicked
        int fila = TablaAdoptante.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "no se ha seleccionado ninguna fila---");
        } else {
            id_adoptante = Integer.parseInt(TablaAdoptante.getValueAt(fila, 0).toString());
            String nombre = TablaAdoptante.getValueAt(fila, 1).toString();
            String apellido_1 = TablaAdoptante.getValueAt(fila, 2).toString();
            String apellido_2 = TablaAdoptante.getValueAt(fila, 3).toString();
            String direccion = TablaAdoptante.getValueAt(fila, 4).toString();
            String ciudad = TablaAdoptante.getValueAt(fila, 5).toString();
            String comunidad_autonoma = TablaAdoptante.getValueAt(fila, 6).toString();
            int codigo_postal = Integer.parseInt(TablaAdoptante.getValueAt(fila, 7).toString());

            //form.setText(variables de arriba)
            txtNombreAdoptante.setText(nombre);
            txtPrimerPellidoAdoptante.setText(apellido_1);
            txtSegundoPellidoAdoptante.setText(apellido_2);
            txtDireccionAdoptante.setText(direccion);
            txtCiudadAdoptante.setText(ciudad);
            jComboBox1.setSelectedItem(comunidad_autonoma);
            txtCodigoPostalAdoptante.setText("" + codigo_postal);
        }
    }//GEN-LAST:event_TablaAdoptanteMouseClicked

    private void tablaPerroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPerroMouseClicked
        int fila = tablaPerro.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "no se ha seleccionado ninguna fila");
        } else {
            id_perro = Integer.parseInt(tablaPerro.getValueAt(fila, 0).toString());
            String nombre = tablaPerro.getValueAt(fila, 1).toString();
            String raza = tablaPerro.getValueAt(fila, 2).toString();
            int fecha = Integer.parseInt(tablaPerro.getValueAt(fila, 3).toString());
            String direccion_perrera = tablaPerro.getValueAt(fila, 4).toString();
            estado=Boolean.parseBoolean(tablaPerro.getValueAt(fila, 5).toString());

            //form.setText(variables de arriba)
            txtNombre.setText(nombre);
            txtRaza.setText(raza);
            txtFecha_Nacimiento.setText("" + fecha);
            txtDireccionPerrera.setText(direccion_perrera);

        }
    }//GEN-LAST:event_tablaPerroMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = tablaPerro.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona perro!");
        } else {
            Object[] o = new Object[5];
            o[0] = txtNombre.getText();
            o[1] = txtRaza.getText();
            o[2] = txtFecha_Nacimiento.getText();
            o[3] = txtDireccionPerrera.getText();
            o[4] = id_perro;

            p.actualizar(o);
        }
        limpiarTabla(modeloPerroTabla);
        limpiarLabelesPerro();
        rellenameTablaPerro();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fila = tablaPerro.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "selecciona perro");
        } else {
            p.eliminar(id_perro);
            limpiarTabla(modeloPerroTabla);
            limpiarLabelesPerro();
            rellenameTablaPerro();
            rellenameTablaAdoptante();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtNombre.getText().equals("") || txtRaza.getText().equals("") || txtFecha_Nacimiento == null
                || txtDireccionPerrera.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Faltan datos");
        } else {
            Object[] o = new Object[4];
            o[0] = txtNombre.getText();
            o[1] = txtRaza.getText();
            o[2] = txtFecha_Nacimiento.getText();
            o[3] = txtDireccionPerrera.getText();

            p.guardar(o);
        }
        limpiarTabla(modeloPerroTabla);
        limpiarLabelesPerro();
        rellenameTablaPerro();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int fila = TablaAdoptante.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "selecciona adoptante");
        } else {
            Object[] o = new Object[8];
            o[0] = txtNombreAdoptante.getText();
            o[1] = txtPrimerPellidoAdoptante.getText();
            o[2] = txtSegundoPellidoAdoptante.getText();
            o[3] = txtDireccionAdoptante.getText();
            o[4] = txtCiudadAdoptante.getText();
            o[5] = jComboBox1.getSelectedItem().toString();
            o[6] = txtCodigoPostalAdoptante.getText();
            o[7] = id_adoptante;
            ate.actualizar(o);
        }
        limpiarLabelsAdoptante();
        limpiarTabla(modeloAdoptanteTabla);
        rellenameTablaAdoptante();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // add adoptante
        Object[] o = new Object[7];
        o[0] = txtNombreAdoptante.getText();
        o[1] = txtPrimerPellidoAdoptante.getText();
        o[2] = txtSegundoPellidoAdoptante.getText();
        o[3] = txtDireccionAdoptante.getText();
        o[4] = txtCiudadAdoptante.getText();
        o[5] = jComboBox1.getSelectedItem().toString();
        o[6] = txtCodigoPostalAdoptante.getText();
        ate.guardar(o);
        limpiarLabelsAdoptante();
        limpiarTabla(modeloAdoptanteTabla);
        rellenameTablaAdoptante();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int fila = TablaAdoptante.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "selecciona adoptante");
        } else {
            ate.eliminar(id_adoptante);
            limpiarLabelsAdoptante();
            limpiarTabla(modeloAdoptanteTabla);
            rellenameTablaAdoptante();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (estado == true || estado) {
            JOptionPane.showMessageDialog(this, "este perro ya esta adoptado");
        } else {

            int fila_perro = tablaPerro.getSelectedRow();
            int fila_adoptante = TablaAdoptante.getSelectedRow();
            if (fila_perro == -1 || fila_adoptante == -1) {
                JOptionPane.showMessageDialog(this, "debes seleccionar tanto al perro como al adoptante!!!");
            } else {
                ContratoAdopcion a = new ContratoAdopcion(id_perro, id_adoptante,this);
                a.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "introduce valor de busqueda");
        }
        switch (cmBoxCategoriaBusqueda.getSelectedItem().toString()) {
            case "SELECCIONA BUSQUEDA":
                JOptionPane.showMessageDialog(this, "no has seleccionado categoria de busqueda");
                break;
            case "NOMBRE PERRO":
                sql = "select * from perro where nombre=?;";
                parametroBusqueda = txtBuscar.getText();
                limpiarTabla(modeloPerroTabla);
                rellenameTablaPerroBuscar(sql, parametroBusqueda);

                break;
            case "RAZA":
                sql = "select * from perro where raza=?;";
                parametroBusqueda = txtBuscar.getText();
                limpiarTabla(modeloPerroTabla);
                rellenameTablaPerroBuscar(sql, parametroBusqueda);

                break;
            case "CIUDAD ADOPTANTE":
                sql = "select * from adoptante where ciudad=?";
                parametroBusqueda = txtBuscar.getText();
                limpiarTabla(modeloAdoptanteTabla);
                rellenameTablaAdoptanteBuscar(sql, parametroBusqueda);

                break;
            case "CODIGO POSTAL ADOPTANTE":
                sql = "select * from adoptante where codigo_postal=?";
                parametroBusqueda = txtBuscar.getText();
                limpiarTabla(modeloAdoptanteTabla);
                rellenameTablaAdoptanteBuscar(sql, parametroBusqueda);

                break;
            case "COMUNIDAD AUTONOMA ADOPTANTE":
                sql = "select * from adoptante where comunidad_autonoma=?";
                parametroBusqueda = txtBuscar.getText();
                limpiarTabla(modeloAdoptanteTabla);
                rellenameTablaAdoptanteBuscar(sql, parametroBusqueda);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tableAdopcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdopcionMouseClicked
        int fila = tableAdopcion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "selecciona adopcion que se quiere romper contrato!!!");
        } else {
            id_adopcion = Integer.parseInt(tableAdopcion.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_tableAdopcionMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        acion.eliminar(id_adopcion);
        limpiarTabla(modeloAdopcionTabla);
        rellenameTablaAdopcion();
    }//GEN-LAST:event_jButton9ActionPerformed
    public DefaultTableModel rellenameTablaPerro() {
        List<Perro> miLista = p.dameTodo();
        modeloPerroTabla = (DefaultTableModel) tablaPerro.getModel();
        Object[] o = new Object[6];
        for (int i = 0; i < miLista.size(); i++) {
            o[0] = miLista.get(i).getId_perro();
            o[1] = miLista.get(i).getNombre();
            o[2] = miLista.get(i).getRaza();
            o[3] = miLista.get(i).getAnno();
            o[4] = miLista.get(i).getDireccion();
            o[5] = miLista.get(i).getEstado();
            modeloPerroTabla.addRow(o);
        }
        return modeloPerroTabla;

    }

    public DefaultTableModel rellenameTablaAdopcion() {
        List<Adopcion> miLista = acion.dameTodo();
        modeloAdopcionTabla = (DefaultTableModel) tableAdopcion.getModel();
        Object[] o = new Object[8];
        for (int i = 0; i < miLista.size(); i++) {
            o[0] = miLista.get(i).getId_adopcion();
            o[1] = miLista.get(i).getFecha();
            o[2] = miLista.get(i).getNombre_perro();
            o[3] = miLista.get(i).getNombre_adoptante() + " " + miLista.get(i).getApellido_1_adoptante() + " "
                    + miLista.get(i).getApellido_2_adoptante();
            o[4] = miLista.get(i).getDireccion_adoptante();
            modeloAdopcionTabla.addRow(o);
        }
        return modeloAdoptanteTabla;

    }

    private DefaultTableModel rellenameTablaPerroBuscar(String sql, String parametroBusqueda) {
        List<Perro> miLista = p.dameBusquedaPerro(sql, txtBuscar.getText());
        modeloPerroTabla = (DefaultTableModel) tablaPerro.getModel();
        Object[] o = new Object[6];
        for (int i = 0; i < miLista.size(); i++) {
            o[0] = miLista.get(i).getId_perro();
            o[1] = miLista.get(i).getNombre();
            o[2] = miLista.get(i).getRaza();
            o[3] = miLista.get(i).getAnno();
            o[4] = miLista.get(i).getDireccion();
            o[5] = miLista.get(i).getEstado();
            modeloPerroTabla.addRow(o);
        }
        return modeloPerroTabla;

    }

    private DefaultTableModel rellenameTablaAdoptanteBuscar(String sql, String parametroBusqueda) {
        List<Adoptante> miLista = ate.dameBusquedaAdoptante(sql, parametroBusqueda);
        modeloAdoptanteTabla = (DefaultTableModel) TablaAdoptante.getModel();
        Object[] o = new Object[8];
        for (int i = 0; i < miLista.size(); i++) {
            o[0] = miLista.get(i).getId_adoptante();
            o[1] = miLista.get(i).getNombre();
            o[2] = miLista.get(i).getApelido_1();
            o[3] = miLista.get(i).getApellido_2();
            o[4] = miLista.get(i).getDireccion();
            o[5] = miLista.get(i).getCiudad();
            o[6] = miLista.get(i).getComunidad_autonoma();
            o[7] = miLista.get(i).getCodigo_postal();
            modeloAdoptanteTabla.addRow(o);
        }
        return modeloAdoptanteTabla;

    }

    private DefaultTableModel rellenameTablaAdoptante() {
        List<Adoptante> miLista = ate.dameTodo();
        modeloAdoptanteTabla = (DefaultTableModel) TablaAdoptante.getModel();
        Object[] o = new Object[8];
        for (int i = 0; i < miLista.size(); i++) {
            o[0] = miLista.get(i).getId_adoptante();
            o[1] = miLista.get(i).getNombre();
            o[2] = miLista.get(i).getApelido_1();
            o[3] = miLista.get(i).getApellido_2();
            o[4] = miLista.get(i).getDireccion();
            o[5] = miLista.get(i).getCiudad();
            o[6] = miLista.get(i).getComunidad_autonoma();
            o[7] = miLista.get(i).getCodigo_postal();
            modeloAdoptanteTabla.addRow(o);
        }
        return modeloAdoptanteTabla;

    }

    private void limpiarLabelesPerro() {
        txtNombre.setText("");
        txtFecha_Nacimiento.setText("");
        txtRaza.setText("");
        txtFecha_Nacimiento.setText("");
        txtDireccionPerrera.setText("");
    }

    private void limpiarLabelsAdoptante() {
        txtNombreAdoptante.setText("");
        txtPrimerPellidoAdoptante.setText("");
        txtSegundoPellidoAdoptante.setText("");
        txtDireccionAdoptante.setText("");
        txtCiudadAdoptante.setText("");
        txtCodigoPostalAdoptante.setText("");
        jComboBox1.setSelectedItem(ABORT);
    }

    public void limpiarTabla(DefaultTableModel miModelo) {
        for (int i = 0; i < miModelo.getRowCount(); i++) {
            miModelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAdoptante;
    private javax.swing.JComboBox<String> cmBoxCategoriaBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaPerro;
    private javax.swing.JTable tableAdopcion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCiudadAdoptante;
    private javax.swing.JTextField txtCodigoPostalAdoptante;
    private javax.swing.JTextField txtDireccionAdoptante;
    private javax.swing.JTextField txtDireccionPerrera;
    private javax.swing.JTextField txtFecha_Nacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAdoptante;
    private javax.swing.JTextField txtPrimerPellidoAdoptante;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtSegundoPellidoAdoptante;
    // End of variables declaration//GEN-END:variables
}
